version: "3"

services:
    nginx:
        restart: always
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - 80:80
        depends_on:
            - app
        container_name: ecoproject_nginx

    app:
        restart: always
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        container_name: ecoproject_app
        depends_on:
            - db

    db:
        restart: always
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: ecoproject
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: ecoproject_db

    phpmyadmin:
        restart: always
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8153:80
        container_name: ecoproject_phpmyadmin
